services:
  front:
    image: "${REGISTRY_LOCATION}/chess-front:${CHESS_FRONT_TAG:-latest}"
    environment:
       REACT_APP_ARBITRATOR_URL: "${DEPLOY_DOMAIN:-localhost}:${ARBITRATOR_PORT:-8080}"
    command:
      - "./scripts/pod_init.sh"
    ports:
      - "80:3000"
    networks:
      - external
      - internal

#  front-proxy:
#    image: gcr.io/compact-pier-403417/github.com/cameronhonis/nginx-proxy:latest
#    environment:
#      PROXY_IN_PORT: "8081"
#      PROXY_OUT_PORT: "8080"
#      PROXY_OUT_ADDR: "arbitrator"
#    command:
#      - "./scripts/pod_init.sh"
#    ports:
#      - "8081:8081"
#    networks:
#      - external
#      - internal

  arbitrator:
    image: "${REGISTRY_LOCATION}/chess-arbitrator:${CHESS_ARBITRATOR_TAG:-latest}"
    environment:
      LISTEN_PORT: "${ARBITRATOR_PORT:-8080}"
      BOT_CLIENT_SECRET: "${BOT_CLIENT_SECRET}"
    command:
      - "./scripts/pod_init.sh"
    ports:
      - "${ARBITRATOR_PORT:-8080}:${ARBITRATOR_PORT:-8080}"
    networks:
      - external
      - internal

  bot-server:
    image: "${REGISTRY_LOCATION}/chess-bot-server:${CHESS_BOT_SERVER_TAG:-latest}"
    environment:
      BOT_CLIENT_SECRET: "${BOT_CLIENT_SECRET}"
      ARBITRATOR_DOMAIN: "arbitrator"
      ARBITRATOR_PORT: "${ARBITRATOR_PORT:-8080}"
    command:
      - "./main"
    ports:
      - "${BOT_SERVER_PORT:-8082}:${BOT_SERVER_PORT:-8082}"
    networks:
      - internal
networks:
  external:
    external: true
  internal:
    internal: true