# clone of sibling file compose.yml. Exists to allow for local builds.
services:
  front:
    image: "chess-front:${CHESS_FRONT_TAG:-latest}"
    environment:
      REACT_APP_ARBITRATOR_DOMAIN: "${ARBITRATOR_DOMAIN:-localhost}"
      REACT_APP_ARBITRATOR_PORT: "${ARBITRATOR_PORT}"
    command:
      - "./scripts/pod_init.sh"
    ports:
      - "3000:3000"
    networks:
      - external
      - internal

  arbitrator:
    image: "chess-arbitrator:${CHESS_ARBITRATOR_TAG:-latest}"
    environment:
      LISTEN_PORT: "${ARBITRATOR_PORT:-8080}"
      BOT_CLIENT_SECRET: "${BOT_CLIENT_SECRET}"
    command:
      - "./scripts/pod_init.sh"
    ports:
      - "${ARBITRATOR_PORT:-8080}:${ARBITRATOR_PORT:-8080}"
    networks:
      - external
      - internal

  bot-server:
    image: "chess-bot-server:${CHESS_BOT_SERVER_TAG:-latest}"
    environment:
      BOT_CLIENT_SECRET: "${BOT_CLIENT_SECRET}"
      ARBITRATOR_DOMAIN: "arbitrator"
      ARBITRATOR_PORT: "${ARBITRATOR_PORT:-8080}"
    command:
      - "./main"
    ports:
      - "${BOT_SERVER_PORT:-8082}:${BOT_SERVER_PORT:-8082}"
    networks:
      - internal
networks:
  external:
    external: true
  internal:
    internal: true