---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "arbitrator"
  namespace: "default"
  labels:
    app: "arbitrator"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "arbitrator"
  template:
    metadata:
      labels:
        app: "arbitrator"
    spec:
      containers:
        - name: "chess-arbitrator-sha256-1"
          image: "gcr.io/compact-pier-403417/github.com/cameronhonis/chess-arbitrator:latest"
