---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "arbitrator-service"
  namespace: "default"
  labels:
    app: "arbitrator"
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: "arbitrator"
  type: "LoadBalancer"
