---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "front-deployment"
  namespace: "default"
  labels:
    app: "front"
#    type: "deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "front"
#      type: "node"
  template:
    metadata:
      labels:
        app: "front"
#        type: "pod"
    spec:
      containers:
      - name: "front"
        image: "gcr.io/compact-pier-403417/chess-client@sha256:6b66704fe06ff87d5440e4ef0c77b81cf0bcbe760628cacbb26194ce8d504ddf"
