apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o conv
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: arbitrator
  name: arbitrator
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: arbitrator
