apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o convd/
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: bot-server
  name: bot-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bot-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o convd/
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/docker-internal: "true"
        io.kompose.service: bot-server
    spec:
      containers:
        - args:
            - ./main
          env:
            - name: BOT_CLIENT_SECRET
              value: "bot_client_secret"
            - name: ARBITRATOR_DOMAIN
              value: "arbitrator"
            - name: ARBITRATOR_PORT
              value: "8080"
          image: gcr.io/compact-pier-403417/github.com/cameronhonis/chess-bot-server:latest
          name: bot-server
          ports:
            - containerPort: 8082
              protocol: TCP
      imagePullSecrets:
        - name: pull-image

      restartPolicy: Always
