apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o conv
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: front
  name: front
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 3000
  selector:
    io.kompose.service: front
  type: LoadBalancer